import React, { useEffect, useMemo, useRef, useState } from 'react'
import vettamStill from './assets/vettam-regretify.jpeg'

const rupees = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })
const foods = [{ emoji: '🥚', name: 'MUTTA', price: 12, line: 'That’s a LOT of omelettes.' }, { emoji: '🥐', name: 'PUFFS', price: 20, line: 'A flaky little trade-off.' }, { emoji: '🍛', name: 'BIRIYANI', price: 160, line: 'Headphones over five biriyanis?' }, { emoji: '☕', name: 'CHAYA', price: 12, line: 'A tea break for the whole class.' }]
const scoreFor = amount => Math.min(99, Math.max(4, Math.round(18 + Math.log10(Math.max(amount, 1)) * 21)))
const trafficFor = score => score <= 20 ? ['Chill', 'green', 'Carry on, sensible citizen.'] : score <= 40 ? ['Hmm', 'yellow', 'A small pause would not hurt.'] : score <= 60 ? ['Bro...', 'orange', 'Bro, maybe close the checkout page.'] : score <= 80 ? ['Stop', 'red', 'Step away from the payment button.'] : ['Goodbye Money', 'black', 'Your wallet has filed a missing-person report.']
function historyFromStorage() { try { const items = JSON.parse(localStorage.getItem('regretify-history') || '[]'); return Array.isArray(items) ? items : [] } catch { return [] } }
function makeId() { return `RG-${Math.random().toString(36).slice(2, 6).toUpperCase()}-${Math.floor(1000 + Math.random() * 9000)}` }
function FoodCard({ food, quantity, index }) { return <article className="food-card" style={{ '--entrance-delay': `${index * 90}ms` }}><div className="food-card-topline"><span className="food-emoji">{food.emoji}</span><span>₹{food.price} each</span></div><h3>{food.name}</h3><strong>{quantity}</strong><span className="food-unit">{food.name.toLowerCase()}</span><p>{food.line}</p></article> }

export default function App() {
  const [savingsInput, setSavingsInput] = useState(() => localStorage.getItem('regretify-savings') || '')
  const [savings, setSavings] = useState(() => Number(localStorage.getItem('regretify-savings')) || 0)
  const [purchase, setPurchase] = useState(null); const [form, setForm] = useState({ product: '', price: '' })
  const [history, setHistory] = useState(historyFromStorage); const [soundOn, setSoundOn] = useState(() => localStorage.getItem('regretify-sounds') !== 'off')
  const [citizenId] = useState(() => localStorage.getItem('regretify-citizen-id') || makeId()); const [pendingDelete, setPendingDelete] = useState(null); const [toast, setToast] = useState(''); const resultRef = useRef(null); const audioContextRef = useRef(null)
  useEffect(() => { if (savings > 0) localStorage.setItem('regretify-savings', savings) }, [savings]); useEffect(() => localStorage.setItem('regretify-history', JSON.stringify(history)), [history]); useEffect(() => localStorage.setItem('regretify-sounds', soundOn ? 'on' : 'off'), [soundOn]); useEffect(() => localStorage.setItem('regretify-citizen-id', citizenId), [citizenId]); useEffect(() => { if (purchase) resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }, [purchase]); useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3200); return () => clearTimeout(timer) }, [toast])
  const foodResults = useMemo(() => purchase ? foods.map(food => ({ ...food, quantity: Math.floor(purchase.price / food.price) })) : [], [purchase]); const currentScore = purchase?.score; const avgScore = history.length ? Math.round(history.reduce((sum, item) => sum + item.score, 0) / history.length) : 0; const activeScore = currentScore ?? avgScore; const [trafficName, trafficColor, trafficNote] = trafficFor(activeScore); const total = history.reduce((sum, item) => sum + item.price, 0); const regretLevel = activeScore <= 20 ? 'Responsible Citizen' : activeScore <= 40 ? 'Questionable Citizen' : activeScore <= 60 ? 'Professional' : activeScore <= 80 ? 'Financially Unstable' : 'Certified Wallet Destroyer'; const walletStatus = activeScore <= 20 ? 'Healthy' : activeScore <= 40 ? 'Slightly Complicated' : activeScore <= 60 ? 'Under Observation' : activeScore <= 75 ? 'Complicated' : activeScore <= 88 ? 'Critical' : 'Goodbye Money'
  async function sound(score, preview = false) { try { const Ctx = window.AudioContext || window.webkitAudioContext; if (!Ctx) return; const ctx = audioContextRef.current || new Ctx(); audioContextRef.current = ctx; if (ctx.state === 'suspended') await ctx.resume(); const notes = preview ? [660] : score > 80 ? [165, 138, 110] : score > 60 ? [330, 247] : [523]; notes.forEach((frequency, index) => { const oscillator = ctx.createOscillator(), gain = ctx.createGain(), start = ctx.currentTime + index * .16; oscillator.type = score > 80 ? 'sawtooth' : score > 60 ? 'square' : 'sine'; oscillator.frequency.setValueAtTime(frequency, start); gain.gain.setValueAtTime(.0001, start); gain.gain.exponentialRampToValueAtTime(preview ? .13 : .16, start + .015); gain.gain.exponentialRampToValueAtTime(.0001, start + .13); oscillator.connect(gain).connect(ctx.destination); oscillator.start(start); oscillator.stop(start + .15) }) } catch {} }
  function submit(event) { event.preventDefault(); const price = Number(form.price); if (!form.product.trim() || price <= 0) return; const item = { id: `${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, product: form.product.trim(), price, score: scoreFor(price), createdAt: new Date().toISOString() }; setPurchase(item); setHistory(items => [item, ...items]); sound(item.score) }
  function confirmDelete() { setHistory(items => items.filter(item => item.id !== pendingDelete.id)); setPendingDelete(null); setToast('Evidence removed. Regret remains. 💀') }
  const biriyani = foodResults.find(food => food.name === 'BIRIYANI'), chaya = foodResults.find(food => food.name === 'CHAYA'), mutta = foodResults.find(food => food.name === 'MUTTA')
  function toggleSound() { if (!soundOn) sound(40, true); setSoundOn(value => !value) }
  return <main className="app-shell" id="top"><header className="topbar"><a className="brand" href="#top"><b>☹</b> REGRETIFY</a><nav aria-label="Main navigation"><a href="#top">Home</a><a href="#confess">Calculate</a><a href="#archive">My regrets</a></nav><button className="sound-toggle" type="button" aria-pressed={soundOn} onClick={toggleSound}>🔊 Traffic sounds: {soundOn ? 'ON' : 'OFF'}</button></header>
    <section className="hero" aria-labelledby="hero-heading"><div className="hero-copy"><p className="kicker">The unnecessary spending companion</p><h1 id="hero-heading">Before you buy it...<br /><em>onnu aalochichittu</em><br />vaangikko.</h1><p className="hero-summary">Enter the amount and product name. Find out enthellam you could&rsquo;ve had instead. No judgment. Okay, a little judgment.</p><a className="hero-action" href="#confess">Regretify it <span>✦</span></a></div><div className="hero-scene"><span className="hero-scribble scribble-top" aria-hidden="true">See what you could have bought ↗</span><span className="hero-scribble scribble-left" aria-hidden="true">Select your<br />regret category</span><span className="hero-scribble scribble-label" aria-hidden="true">Select your regret category</span><span className="hero-scribble scribble-right" aria-hidden="true">See what you<br />could have bought</span><span className="scene-note note-one" aria-hidden="true">01</span><span className="scene-note note-two" aria-hidden="true">✦</span><div className="tv-set"><div className="tv-screen"><img src={vettamStill} alt="Two characters considering a purchase on a train" /></div></div><p className="hero-speech">Onnu aalochichittu<br />vaangikko</p><span className="hero-prop prop-car" aria-hidden="true">🚗 That unnecessary accessory</span><span className="hero-prop prop-watch" aria-hidden="true">⌚ Luxury watch</span></div></section>
    <section className="calculator-section" id="confess"><div className="section-intro"><p className="kicker">The regret calculator</p><h2>A small moment of<br /><em>honesty.</em></h2><p>Give us the amount and the product. We’ll do the rest.</p></div><div className="calculator-grid"><section className="savings-card"><div className="card-topline"><span>01 / YOUR BASELINE</span><span>Private by design</span></div><h3>What’s in the vault?</h3><form onSubmit={event => { event.preventDefault(); const value = Number(savingsInput); if (value > 0) setSavings(value) }} className="savings-form"><label htmlFor="savings">Current savings</label><div className="money-input"><span>₹</span><input id="savings" type="number" min="0" value={savingsInput} onChange={event => setSavingsInput(event.target.value)} /></div><button className="text-button">Save this number <span>→</span></button></form><p className="saved-value">{savings ? `Currently guarding ${rupees.format(savings)}` : 'Add a number so we can judge responsibly.'}</p></section><section className="purchase-card"><div className="card-topline"><span>02 / THE TEMPTATION</span><span>Be brave</span></div><h3>Confess the purchase.</h3><form onSubmit={submit} className="purchase-form"><label htmlFor="price">Product amount</label><div className="money-input"><span>₹</span><input id="price" type="number" name="price" min="1" value={form.price} onChange={event => setForm({ ...form, price: event.target.value })} required /></div><div className="quick-amounts">{[500, 1000, 2500, 5000].map(amount => <button key={amount} type="button" onClick={() => setForm({ ...form, price: String(amount) })}>₹{amount.toLocaleString('en-IN')}</button>)}</div><label htmlFor="product">Product name</label><input id="product" name="product" value={form.product} onChange={event => setForm({ ...form, product: event.target.value })} required /><button className="primary-button">Give me the food report <span>→</span></button></form></section></div></section>
    {purchase && <section className="food-report" ref={resultRef} aria-live="polite"><div className="report-heading"><p className="kicker">FINANCIAL DAMAGE REPORT</p><h2>{purchase.price.toLocaleString('en-IN')} roopa undayirunnenkil enthoram...</h2></div><div className="food-grid">{foodResults.map((food, index) => <FoodCard key={food.name} food={food} quantity={food.quantity} index={index} />)}</div><p className="personalised-regret">{biriyani.quantity ? `That ${purchase.product} costs ${biriyani.quantity} biriyanis — or ${chaya.quantity} chayas.` : `That ${purchase.product} costs ${mutta.quantity} eggs. Small amount, real snacks.`}</p><section className="score-section"><p className="kicker">REGRET SCORE</p><strong>{currentScore}%</strong><p>{currentScore < 40 ? 'You’re probably fine.' : currentScore <= 64 ? 'Hmm… maybe think twice.' : currentScore <= 83 ? 'This purchase is getting suspicious.' : 'This needs a proper second look.'}</p></section></section>}
    <section className="chaos-archive" id="archive"><p className="kicker">OFFICIAL REGRETIFY RECORDS</p><h2>Your regret archive.</h2><div className="chaos-grid"><article className="citizen-card"><p className="kicker">REGRETIFY CITIZEN</p><span>{citizenId}</span><h3>Officially observed.</h3><dl><div><dt>Regret level</dt><dd>{regretLevel}</dd></div><div><dt>Wallet status</dt><dd>{walletStatus}</dd></div></dl></article><article className="traffic-card"><p className="kicker">FINANCIAL TRAFFIC LIGHT</p><div className="lights" aria-label={`Current financial traffic light: ${trafficName}`}>{['green', 'yellow', 'orange', 'red', 'black'].map(color => <span key={color} className={`light ${color} ${color === trafficColor ? 'active' : ''}`} />)}</div><b>{trafficName}</b><p>{trafficNote}</p><button type="button" className="traffic-sound-button" onClick={() => sound(activeScore)} disabled={!soundOn}>{soundOn ? 'Play traffic signal' : 'Turn sounds on first'}</button></article><article className="archive-stats"><p className="kicker">DAMAGE SO FAR</p><strong>{rupees.format(total)}</strong><p>{history.length} purchase{history.length === 1 ? '' : 's'} · {avgScore}% average regret</p></article></div><section className="history-list"><div><h3>Evidence locker</h3><span>{history.length} record{history.length === 1 ? '' : 's'}</span></div>{history.length ? <ul>{history.map(item => <li key={item.id}><div><strong>{item.product}</strong><span>{item.score}% regret · {new Date(item.createdAt).toLocaleDateString('en-IN')}</span></div><b>{rupees.format(item.price)}</b><button onClick={() => setPendingDelete(item)}>Delete</button></li>)}</ul> : <p>Your future financial evidence will appear here.</p>}</section></section>
    <section className="marquee"><div className="marquee-track"><span>Some purchases are worth it. <b>Some purchases need a second look.</b></span><span>Some purchases are worth it. <b>Some purchases need a second look.</b></span></div></section><section className="how-it-works"><p className="kicker">THE VERY SCIENTIFIC METHOD</p><h2>Spend.<br />Count snacks.<br /><em>Reconsider.</em></h2><p>We turn the price tag into things you actually understand.</p></section><footer><span>REGRETIFY®</span><p>Making bad financial decisions slightly more visible.</p><span>Prices are approximate reference values.</span></footer>
    {pendingDelete && <div className="dialog-backdrop"><section className="regret-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><p className="kicker">A SMALL ADMINISTRATIVE MATTER</p><h2 id="delete-title">You can delete the record.</h2><p>You cannot delete the regret.</p><div><button className="delete-anyway" onClick={confirmDelete}>Delete it anyway</button><button className="cancel-delete" onClick={() => setPendingDelete(null)}>Cancel</button></div></section></div>}{toast && <div className="regret-toast" role="status">{toast}</div>}</main>
}
